version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-test
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=woovi-playground-test
    restart: always
